name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: wasm32v1-none
        components: rustfmt, clippy

    - name: Check Formatting
      run: cargo fmt --check

    - name: Clippy Lints
      run: cargo clippy -- -D warnings

    - name: Run Tests
      run: cargo test --features testutils

    - name: Build WASM
      run: cargo build --target wasm32v1-none --release
